name: settings_api
description: The interface and models for an API providing access to app settings.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  test: ^1.24.6
  very_good_analysis: ^5.1.0
