name: advanced_internationalization
description: basic project handling advanced internationalization
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  intl: any # An exact version pin will be provided by the Flutter SDK
  local_storage_settings_api:
    path: packages/local_storage_settings_api
  settings_api:
    path: packages/settings_api
  settings_repository:
    path: packages/settings_repository

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test_cov_console: ^0.2.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true # Enables generation of localized strings from arb files
