import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

export 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Extension on [BuildContext] to simplify the access to localized strings.
///
/// This extension adds a getter [l10n] on [BuildContext] to obtain an instance
/// of [AppLocalizations] generated by Flutter's localization system.
///
/// Usage example:
/// ```dart
/// final localizedString = context.l10n.someLocalizedString;
/// ```
extension AppLocalizationsX on BuildContext {
  /// Gets the localized strings using [AppLocalizations.of].
  ///
  /// This acts as a shorthand to easily get an instance of [AppLocalizations]
  /// for the current context.
  AppLocalizations get l10n => AppLocalizations.of(this);
}
